fix(Blockchain jobs): Reimplemented the build scan push blockchain image to now test the fabric network before it is run by the CD pipeline

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -12,6 +12,9 @@ jobs:
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/develop' && ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
       - name: Install Docker Compose
         run: |
           if ! [ -x "$(command -v docker-compose)" ]; then
@@ -23,67 +26,61 @@ jobs:
           fi
           docker-compose --version
 
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
-      - name: Select Tagging Scheme
-        id: get_tag
+      - name: Deploy Pesachain Blockchain (Dev)
         run: |
-          TAG=$(git tag --points-at HEAD)
-          if [ -z "$TAG" ]; then
-            echo "No tags found in the latest commit. Using commit hash."
-            echo "git_tag=${GITHUB_SHA}" >> $GITHUB_ENV
-          else
-            echo "Using tag from the latest commit: $TAG"
-            echo "git_tag=$TAG" >> $GITHUB_ENV
-          fi
+          # Orderer Service
+          ORDERER_CA_YAML_FILE=./Blockchain/Hyperledger/Orderer/ca-orderer.yaml
+          ORDERER_NODES_COMPOSE_FILE=./Blockchain/Hyperledger/docker-compose-orderer.yaml
 
-      - name: Set IMAGE_TAG for Development
-        run: |
-          echo "IMAGE_TAG=$IMAGE_TAG"
-          echo "IMAGE_TAG=dev-${{ env.git_tag }}" >> $GITHUB_ENV
+          docker-compose -f $ORDERER_CA_YAML_FILE up -d
+          docker-compose -f $ORDERER_NODES_COMPOSE_FILE up -d
 
-      # Parallel deployment of Docker images for development
-      - name: Deploy Pesachain (Dev)
-        run: |
-          docker compose -f docker-compose.yml pull
-          docker compose -f docker-compose.yml up -d
+          # Pesachain Organization
+          PESACHAIN_CA_YAML_FILE=./Blockchain/Hyperledger/Pesachain/ca-pesachain.yaml
+          PESACHAIN_PEERS_COMPOSE_FILE=./Blockchain/Hyperledger/docker-compose-peer.yaml
 
-      # Wait for services to start
-      - name: Wait for Services to Start
-        run: sleep 60
+          docker-compose -f $PESACHAIN_CA_YAML_FILE up -d
+          docker-compose -f $PESACHAIN_PEERS_COMPOSE_FILE up -d
 
-      # Health Checks
-      - name: Health Check for Blockchain Service
-        run: |
-          if ! curl --fail http://localhost:4000/health; then
-            echo "Blockchain service health check failed. Investigate the issue."
-            exit 1
-          fi
+          # Organization 2
+          ORG2_CA_YAML_FILE=./Blockchain/Hyperledger/org2/ca-org2.yaml
+          ORG2_PEERS_COMPOSE_FILE=./Blockchain/Hyperledger/docker-compose-peer.yaml
 
-      - name: Health Check for Backend Service
-        run: |
-          if ! curl --fail http://localhost:3000/health; then
-            echo "Backend service health check failed. Investigate the issue."
-            exit 1
-          fi
+          docker-compose -f $ORG2_CA_YAML_FILE up -d
+          docker-compose -f $ORG2_PEERS_COMPOSE_FILE up -d
 
-      - name: Health Check for Web Service
-        run: |
-          if ! curl --fail http://localhost:8080; then
-            echo "Web service health check failed. Investigate the issue."
-            exit 1
-          fi
+      # # Wait for services to start
+      # - name: Wait for Services to Start
+      #   run: sleep 60
 
-      - name: Health Check for Mobile Service
-        run: |
-          if ! curl --fail http://localhost:8081; then
-            echo "Mobile service health check failed. Investigate the issue."
-            exit 1
-          fi
+      # # Health Checks
+      # - name: Health Check for Blockchain Service
+      #   run: |
+      #     if ! curl --fail http://localhost:4000/health; then
+      #       echo "Blockchain service health check failed. Investigate the issue."
+      #       exit 1
+      #     fi
+
+      # - name: Health Check for Backend Service
+      #   run: |
+      #     if ! curl --fail http://localhost:3000/health; then
+      #       echo "Backend service health check failed. Investigate the issue."
+      #       exit 1
+      #     fi
+
+      # - name: Health Check for Web Service
+      #   run: |
+      #     if ! curl --fail http://localhost:8080; then
+      #       echo "Web service health check failed. Investigate the issue."
+      #       exit 1
+      #     fi
+
+      # - name: Health Check for Mobile Service
+      #   run: |
+      #     if ! curl --fail http://localhost:8081; then
+      #       echo "Mobile service health check failed. Investigate the issue."
+      #       exit 1
+      #     fi
 
   # Staging Deployment
   deploy-to-staging:
