fix(docker-compose: command not found): Installed docker compose in the runners

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -12,6 +12,17 @@ jobs:
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/develop' && ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
+      - name: Install Docker Compose
+        run: |
+          if ! [ -x "$(command -v docker-compose)" ]; then
+            echo "Docker Compose not found. Installing..."
+            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            sudo chmod +x /usr/local/bin/docker-compose
+          else
+            echo "Docker Compose is already installed."
+          fi
+          docker-compose --version
+
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -79,6 +90,17 @@ jobs:
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/release/*' && ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
+      - name: Install Docker Compose
+        run: |
+          if ! [ -x "$(command -v docker-compose)" ]; then
+            echo "Docker Compose not found. Installing..."
+            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            sudo chmod +x /usr/local/bin/docker-compose
+          else
+            echo "Docker Compose is already installed."
+          fi
+          docker-compose --version
+
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -146,6 +168,17 @@ jobs:
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/master' && ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
+      - name: Install Docker Compose
+        run: |
+          if ! [ -x "$(command -v docker-compose)" ]; then
+            echo "Docker Compose not found. Installing..."
+            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            sudo chmod +x /usr/local/bin/docker-compose
+          else
+            echo "Docker Compose is already installed."
+          fi
+          docker-compose --version
+
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,6 +61,17 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Install Docker Compose
+        run: |
+          if ! [ -x "$(command -v docker-compose)" ]; then
+            echo "Docker Compose not found. Installing..."
+            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            sudo chmod +x /usr/local/bin/docker-compose
+          else
+            echo "Docker Compose is already installed."
+          fi
+          docker-compose --version
+
       - name: Select Tagging scheme
         id: get_tag
         run: |
@@ -114,6 +125,17 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Install Docker Compose
+        run: |
+          if ! [ -x "$(command -v docker-compose)" ]; then
+            echo "Docker Compose not found. Installing..."
+            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            sudo chmod +x /usr/local/bin/docker-compose
+          else
+            echo "Docker Compose is already installed."
+          fi
+          docker-compose --version
 
       - name: Select Tagging scheme
         id: get_tag
@@ -169,6 +191,17 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Install Docker Compose
+        run: |
+          if ! [ -x "$(command -v docker-compose)" ]; then
+            echo "Docker Compose not found. Installing..."
+            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            sudo chmod +x /usr/local/bin/docker-compose
+          else
+            echo "Docker Compose is already installed."
+          fi
+          docker-compose --version
+
       - name: Select Tagging scheme
         id: get_tag
         run: |
@@ -222,6 +255,17 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Install Docker Compose
+        run: |
+          if ! [ -x "$(command -v docker-compose)" ]; then
+            echo "Docker Compose not found. Installing..."
+            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            sudo chmod +x /usr/local/bin/docker-compose
+          else
+            echo "Docker Compose is already installed."
+          fi
+          docker-compose --version
 
       - name: Select Tagging scheme
         id: get_tag
